### ISSUE TITLE
Sourceds doesn't respond to A2S_PLAYER sometimes

### ISSUE THREAD

**Issue by Douile** [gamedig/node-gamedig#173]
I'm using gamedig to query rust servers using the valve protocol. When the servers have a large amount of player (roughly above 80) they seem to stop responding to A2S_PLAYER packets. This causes a timeout which results in the query failing. This is problematic as my default assumption from a query error is the server is offline. Could the valve query be changed so that if the A2S_PLAYER request times out the value from A2S_INFO is used (players filled with blanks) and the request not error?

**Comment by sonicsnes** [comment]
Yeah, we can probably do that. This is probably ultimately a rust bug though, since the valve protocol defines a packet splitting mechanism to use if the player list won't fit in a standard 1500 byte payload. Sounds like rust is probably not splitting at all, tries to send the invalid packet, and it's getting dropped.

**Comment by Douile** [comment]
Completely agree with that. I have a fork with a workaround if a PR is wanted.

**Comment by mmorrisontx** [comment]
This got fixed at some point.
