### ISSUE TITLE
The emoji seem to break the fivem protocol

### ISSUE THREAD

**Issue by Murgator** [gamedig/node-gamedig#196]
Hello test to query this FiveM server: 91.218.65.57:30120

I obtain this error:

![79cf020e1df386e1c379b43e05c7043a](https://user-images.githubusercontent.com/38978895/95349608-2eac1900-08b7-11eb-810f-66fe92f32891.png)

However, the request works very well from the browser: http://91.218.65.57:30120/info.json

I think these codes have something to do with it and cause the json.PARSE to fail: "Startgeld":"ðŸ’µ | 70.000$","TeamSpeak":"ðŸŽ¤

The same server in port 30125 without emoji work perfectly: 91.218.65.57:30125

Do you have a solution ? Thank you.

**Comment by mmorrisontx** [comment]
To query fivem, it not only needs to respond to info.json and players.json, but it also needs to respond to a quake2 UDP query ping. The quake2 UDP query ping is the only way to receive the server's name, and unfortunately for your server, it appears to be broken -- possibly due to a bug in fivem making it unable to respond to UDP pings when there are unicode characters in the server name (?).

If you don't need the server name, you may be able to remove `await super.run(state);` from `fivem.js` to skip the UDP ping entirely, and gamedig will only return some of the json data back to you.

**Comment by Murgator** [comment]
Hi and thank you for your reply, your solution working fine but i must use an older version. It's possible to do the same with this file ? 
![97737b71aac0c1b4807178bce08a13a6](https://user-images.githubusercontent.com/38978895/95354214-0f63ba80-08bc-11eb-9618-d92c9138b5f7.png)

**Comment by mmorrisontx** [comment]
Not easily, I'd recommend upgrading if possible. If it's not possible, it may just be easier for you to query the server yourself by requesting the json file directly, without using gamedig.

**Comment by Murgator** [comment]
Yes you are right I will create a very simple script with request.js thank you very much for these details the subject is closed !
