### ISSUE TITLE
FiveM ID

### ISSUE THREAD

**Issue by Szabbiii** [gamedig/node-gamedig#219]
How can i store, the id's of the players in a fivem server, like i store the name of them?
Also, how can i store, the state of the server? Like is it offline/online

**Comment by mmorrisontx** [comment]
All information received about players in the server is stored in the player object's `raw` object. If there's no data in there, or the information you are looking for is missing, then it's not available because the server didn't tell us about it.

If the server is offline, the promise will be rejected with an error. Check the readme for details.
