### ISSUE TITLE
Querying a gameserver hosted on the same machine from inside a Docker container doesn't work

### ISSUE THREAD

**Issue by garrappachc** [gamedig/node-gamedig#242]
Hello there,

my case is as follows: I'm hosting a [TF2 dedicated server](https://github.com/melkortf/tf2-servers) and a [Node.JS app](https://github.com/tf2pickup-org/server), both in separate Docker containers, both hosted on the same physical machine. 

_gamedig_ has no problem with querying game servers, even from inside an isolated Docker container:
```bash
$ docker run -it --rm node:latest /bin/bash
root@3f26a62e7cf2:/# npm install -g gamedig
npm WARN deprecated event-to-promise@0.7.0: Use promise-toolbox/fromEvent instead

added 76 packages, and audited 77 packages in 7s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 7.20.3 -> 7.21.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.21.1
npm notice Run npm install -g npm@7.21.1 to update!
npm notice 
root@3f26a62e7cf2:/# gamedig --type tf2 melkor.tf:27105
{"name":"tf2pickup.pl #1","map":"cp_process_f7","password":true,"raw":{"protocol":17,"folder":"tf","game":"TFTrue  ","appId":440,"numplayers":0,"numbots":0,"listentype":"d","environment":"l","secure":1,"version":"6623512","steamid":"90150605346951175","sourcetvport":27110,"sourcetvname":"tf2pickup.pl TV","tags":["cp","nocrits"]},"maxplayers":14,"players":[],"bots":[],"connect":"melkor.tf:27105","ping":43}
root@3f26a62e7cf2:/# 
```

However, when the game server is hosted on the same machine, gamedig times out:
```bash
root@dd231b7c5851:/# gamedig --type tf2 192.168.88.254:27015
{"error":"Failed all 1 attempts"}
root@dd231b7c5851:/# 
```

Launching it with the debug flag the reason becomes obvious:
```bash
root@dd231b7c5851:/# gamedig --type tf2 192.168.88.254:27015 --debug
Q#0 Starting
Q#0 Protocol: Valve
Q#0 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  port: 27015,
  protocol: 'valve',
  requestRules: false,
  type: 'tf2',
  host: '192.168.88.254',
  debug: true
}
Q#0 DNS Lookup: 192.168.88.254
Q#0 Raw IP Address: 192.168.88.254
Q#0 Requesting info ...
192.168.88.254:27015 UDP(47196)-->
Buffer length: 25 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75 
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u  
65 72 79 00 
e  r  y     

172.17.0.1:27015 <--UDP(47196)
Buffer length: 115 bytes
ff ff ff ff 49 11 41 20 54 65 61 6d 20 46 6f 72 74 72 65 73 73 
            I     A     T  e  a  m     F  o  r  t  r  e  s  s  
20 32 20 73 65 72 76 65 72 00 63 70 5f 62 61 64 6c 61 6e 64 73 
   2     s  e  r  v  e  r     c  p  _  b  a  d  l  a  n  d  s  
00 74 66 00 54 46 54 72 75 65 20 20 00 b8 01 00 19 00 64 6c 00 
   t  f     T  F  T  r  u  e                          d  l     
01 36 36 32 33 35 31 32 00 b1 87 69 07 7c d8 ee a8 47 40 01 63 
   6  6  2  3  5  1  2           i     |           G  @     c  
70 2c 69 6e 63 72 65 61 73 65 64 5f 6d 61 78 70 6c 61 79 65 72 
p  ,  i  n  c  r  e  a  s  e  d  _  m  a  x  p  l  a  y  e  r  
73 00 b8 01 00 00 00 00 00 00 
s                             

Q#0 UDP timeout detected
Q#0 Query failed with error Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/usr/local/lib/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Error: Failed all 1 attempts
    at QueryRunner.run (/usr/local/lib/node_modules/gamedig/lib/QueryRunner.js:95:21)
    at async Gamedig.query (/usr/local/lib/node_modules/gamedig/lib/index.js:11:16)
Attempt #1 - Port=27015 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/usr/local/lib/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
root@dd231b7c5851:/# 
```

Docker's NAT translates local gameserver's IP to 172.17.0.1. The gameserver runs in --network=host mode. This issue also appears when I'm running _gamedig_ on a public server, it's not limited to local machines only.

For now, the only workaround is running the app in --network=host mode as well, but this is far from being optimal.

Is there any way to tell _gamedig_ to ignore response IP or whitelist it somehow? Is there a way to handle this case?

**Comment by mmorrisontx** [comment]
If you are going to want to query servers outside of your docker lan (say, over the internet), you'll need to run the gamedig container in host networking mode anyways so it can claim a udp socket on your wan interface.

Another option would be to just query 172.17.0.1:27015 using gamedig (your host ip on the docker lan) instead of 192.168.88.254:27015, and that would probably also work.

If you really want to keep it as is, you could modify https://github.com/gamedig/node-gamedig/blob/master/lib/GlobalUdpSocket.js#L25 to change the fromAddress when it comes in "wrong," but I'd argue that this isn't the proper fix since no other udp protocol would reasonably work when the return IP doesn't match.

**Comment by garrappachc** [comment]
> Another option would be to just query 172.17.0.1:27015 using gamedig (your host ip on the docker lan) instead of 192.168.88.254:27015, and that would probably also work.

The problem is, the address I use for queries is the public one (i.e. all the players see, for example). Using 172.17.0.1:27015 works, but then players won't be use this IP. Workaround here would be to provide some kind of "private" IP address just for UDP queries...

> If you are going to want to query servers outside of your docker lan (say, over the internet), you'll need to run the gamedig container in host networking mode anyways so it can claim a udp socket on your wan interface.

Never had any issues with that, although I know there is an option to use `listenUdpPort`.

I wonder why does the library filter out all IP addresses except the queried one?

**Comment by mmorrisontx** [comment]
> I wonder why does the library filter out all IP addresses except the queried one?

Gamedig supports multiple queries running in parallel, and all responses come into the same udp socket. In order to match the responses back to the queries which made them, it divides them back up based on what address they were returned from.

Even if you aren't running multiple queries at the same time, it's quite common to get udp "junk packets" to random udp ports from random addresses, either delayed responses for queries you've made before, or packets you didn't even ask for. If we didn't filter based on the incoming IP, there'd be no way to tell which packets are junk, and which are actually a response to the query that was made.

**Comment by skylord123** [comment]
I doubt this is a problem with this package.

I host servers off my home network and can query them using my WAN IP address just fine and have been doing it for about a year now. Game servers and gamedig are both running on the same server using Docker on my home network.

I built the package (node-red-contrib-gamedig)[https://www.npmjs.com/package/node-red-contrib-gamedig] and use it to track my own game servers. I have Node-RED running in Bridge mode under docker. You can actually see the data live here:
https://grafana.home.skylar.tech/d/mUeNXzLM9/sven-server?orgId=2&refresh=30s

One thing worth noting is that it's possible the issue is with your networking on either the server or your router (example: accessing your external IP from a device internally on the network may actually send the traffic to your router, it just depends on how the NAT is configured).

**Comment by mmorrisontx** [comment]
Please reopen if you still feel there is an issue here.

**Comment by psych0d0g** [comment]
same issue here, not sure how to fix, i am trying to use gamedig for querying my game servers running on docker on the same server as gamedig, also running in docker, but want to be able to use the host IP to query them.
currently this is my planned setup:
![image](https://user-images.githubusercontent.com/181302/159584076-ffbe20a1-7fea-40a8-97a7-514599005664.png)
the "goal" is some kind of server browser, where users can supply server details on diffrent servers to be added to a php frontend that gets updated with gamedig data for the servers. 
servers beeing on the same host or other hosts in the same lan

use case in this specific setting is to provide a LAN party with ~500 people with a web based server list that is enriched by data from gamedig, and the ability to directly connect to the IP gamedig is fed' to play on the queried server aswell...

**Comment by mmorrisontx** [comment]
Does it work if you query 172.24.0.1 rather than 10.10.10.10? Your machine is doing a form of automatic hairpin nat here, since the packets can't come "from" 10.10.10.10, because that ip isn't on the docker subnet. Worst case, you could probably give the gamedig container host network access, so it wouldn't be on the docker subnet at all.

**Comment by psych0d0g** [comment]
the problem with querying via the internal docker network IP's is, that i have no way of telling gamedig which of the ips it needs to query, basically a user supplies the known to him IP via the nginx/php-fpm frontend, and thats usually the LAN ip of the machine, i guess i really dont have a choice to either put the gamedig container into the host network, or use something like macvlan

**Comment by mmorrisontx** [comment]
> the problem with querying via the internal docker network IP's is, that i have no way of telling gamedig which of the ips it needs to query

Unfortunately, this also means the opposite is true, which is why there's no good solution with your current network setup. If you were able to override which IP gamedig should expect the response packets on, it wouldn't be able to disambiguate which packet is coming from which server, as they all appear to be coming from 172.24.0.1. As it's written now, this would result in all the packets being routed back to every active query, and... that would probably break things. Most query protocol don't contain a nonce in their responses to identify which query they belong to.
