### ISSUE TITLE
Server - Players

### ISSUE THREAD

**Issue by kkm** [gamedig/node-gamedig#261]
![image](https://user-images.githubusercontent.com/134290/148514158-5e2cf05d-028c-4d29-abc4-889438a7a731.png)

it doesn't always show right and it shows blank.
Data bottom name and raw are empty.

Game Server is ARK on official server.

**Comment by mmorrisontx** [comment]
ARK is built on the valve query protocol, which returns two separate pieces of info: a player count, and a list of player details. This sort of output means that the server indicated that it contained 7 players, but then only gave us the names and details for three of them. On some types of servers, this can mean that the other 4 players were bots, or that they were in progress of connecting, but this is all the server sends us and there's no way for us to otherwise fill in those gaps.
