### ISSUE TITLE
maxplayers returns wrong value for servers with > 255 player slots

### ISSUE THREAD

**Issue by Stantastic** [gamedig/node-gamedig#262]
Querying servers with maxplayers above 255 slots returns **44** instead of the actual value. --debug doesnt give additional info.

This was experienced for RUST gameservers, nothing else was tested, the current workaround I'm using is checking the servers tags for the _mpN_ variable which returns mp20 for 20 max players, not sure if that will eventually break.

**Comment by mmorrisontx** [comment]
The valve query protocol only leaves 8 bits of space for the max players count, which means in most implementations it will overflow to 0 rather than 256 (which means I'm guessing your server has 300-256=44 slots). There's not really anything we can do to detect this, unless rust provides the full number in some extra tag info.

**Comment by mmorrisontx** [comment]
Do you have a test server for this? We could probably use the mp tag if it's present.

**Comment by Murgator** [comment]
I confirm that it is necessary to use tags mp if it is present see illustration thank you for your help.

![9dcc73576bac6f7faad744fff5a78fef](https://user-images.githubusercontent.com/38978895/154467005-9f566d3e-1b7a-4e03-992b-c1b0042f80a2.png)

**Comment by mmorrisontx** [comment]
Fixed in 4.0.1 https://github.com/gamedig/node-gamedig/commit/343e23c4adc25090966f1388668c4c48aaa4649d
