### ISSUE TITLE
minecraftpe - motd encoding is broken

### ISSUE THREAD

**Issue by alvin0319** [gamedig/node-gamedig#269]
I used this script:

```javascript
const gamedig = require("gamedig");
(async () => {
    const motd = (await gamedig.query({
        type: "minecraftpe",
        host: "astn.kro.kr",
        port: 19132,
        maxAttempts: 2
    })).raw.gamespy.raw.hostname;
    console.log(motd);
})();
```
It should look like: (접속 복구) 아스타틴 온라인 - Astatine
But it looks like: (� �l) D��� (|x - Astatine

I tried also another server (diamc.kr)

but the result is also similar to this.

I saw someone fixed this by editing this (https://github.com/McbeRank/node-gamedig/commit/4ddeb4f71674894b2e034ca1c13ce9f7c8429ed3)

I have no idea why it looks like this.

Thanks for making this amazing library!

**Comment by mmorrisontx** [comment]
Originally, gamespy3 was marked as using utf8, because the protocol itself is really ancient, and back in its prime time, most games implementing it only supported single byte ascii. However, with more modern games using it as their protocol (for some reason), maybe it's about time that we default them to utf8 and allow users to roll back if they find old games where it shouldn't be used.

BTW, I believe you can override the character set for a single query by passing it in the options.
```
await gamedig.query({
        type: "minecraftpe",
        host: "astn.kro.kr",
        port: 19132,
        maxAttempts: 2,
        encoding: 'utf8'
    }))
```

**Comment by alvin0319** [comment]
> Originally, gamespy3 was marked as using utf8, because the protocol itself is really ancient, and back in its prime time, most games implementing it only supported single byte ascii. However, with more modern games using it as their protocol (for some reason), maybe it's about time that we default them to utf8 and allow users to roll back if they find old games where it shouldn't be used.
> 
> BTW, I believe you can override the character set for a single query by passing it in the options.
> 
> ```
> await gamedig.query({
>         type: "minecraftpe",
>         host: "astn.kro.kr",
>         port: 19132,
>         maxAttempts: 2,
>         encoding: 'utf8'
>     }))
> ```

No, the result is same
