### ISSUE TITLE
feat: query multiple servers in a same request

### ISSUE THREAD

**Issue by Maxence1502** [gamedig/node-gamedig#444]
Hello,

I'd like to get players from dozens of servers at the same time, so I've made a loop with :
`$engine = new Gamedig($server_ip, $server_port, $game_name);`

However, this loop takes far too long. Is it possible to pass several servers as parameters to optimise response time?
For example, this library do this with the "addServer" function: https://github.com/Austinb/GameQ

Thanks

**Comment by CosminPerRam** [comment]
Hmm, the difference shouldn't be "too long", but it also depends on which game (protocol) you use, but it could be that you try to query a server with multiple ports (can be disabled via passing `givenPortOnly: true` to options).

I would be against to adding an "addServer" method as making a query is generaly cheap (in terms of stuff that could be reused) and doing so would require some substantial rework to be added efficiently.

**Comment by Maxence1502** [comment]
With the other library, a request for several dozen servers takes a few seconds; with yours, several requests for the same servers takes almost a minute.
Do you know why there is such a difference?

**Comment by cetteup** [comment]
Have you tried running queries in parallel? Most of the time is usually spent waiting for the server's response, so running queries in sequence means you are spending a lot of time waiting.

I use gamedig to query several hundred game servers every 20 seconds. Works great, even with a limited number of parallel queries.

**Comment by alexevladgabriel** [comment]
There's a little trick there, it is in PHP ecosystem.
I call Gamedig cli as a custom service class and parse the response of json from it.

**Comment by CosminPerRam** [comment]
Hey @Maxence1502, I think #451 could be a strong contester to this performance issue, could you try to add the options `--givenPortOnly`?

**Comment by podrivo** [comment]
I have an Express app that queries some servers from time to time, and adding the option `givenPortOnly` made a noticeable change in reducing loading time.

> I would be against to adding an "addServer" method as making a query is generaly cheap (in terms of stuff that could be reused) and doing so would require some substantial rework to be added efficiently.

Agreed with not adding a feature to query multiple servers in a same request. I would let this to the implementation that uses `gamedig` and not the other way around.

> I call Gamedig cli as a custom service class and parse the response of json from it.

@Maxence1502 Is it possible to call gamedig multiple times, one for each server, instead of a single call with multiple servers?

**Comment by Maxence1502** [comment]
It looks like the response time is the same with or without the parameter :
![image](https://github.com/gamedig/node-gamedig/assets/42026318/95554508-0ecf-44f7-8f8e-6a37a147e2a1)

**Comment by podrivo** [comment]
That's unfortunate... 😔
It seems you'll need to make multiple queries and parse multiple JSONs, instead of a making a single query and wait for a single JSON.

**Comment by Maxence1502** [comment]
In fact the parameter has an impact when the server is not found:
![image](https://github.com/gamedig/node-gamedig/assets/42026318/824070bb-559f-4490-a0d9-2c36e1979544)

However, in my case it doesn't solve my problem, as the servers exists :(

**Comment by Maxence1502** [comment]
@cetteup It's actually a good idea to run the queries in parallel.

It works well but there are so many processes running at the same time that my VPS crashes.
How do you manage to query so many servers without any problems? What kind of machine do you have?

**Comment by CosminPerRam** [comment]
> In fact the parameter has an impact when the server is not found

This is expected behavior, as the library tries (applicable to almost all games) multiple ports to reach a server, whilst passing `givenPortOnly` does a single attempt with the specified N retries.

**Comment by CosminPerRam** [comment]
Hey @Maxence1502, whats the status on this?
Do you still have performance issues with discussed things considered?

**Comment by Maxence1502** [comment]
I run this in parallel in a docker container and it works pretty well

**Comment by CosminPerRam** [comment]
Unfortunately, I don't really see adding this to be worth it as it can be easily made using own logic (loops, Promise.all etc).

The discussion around here has also gone more about the performance of a query rather than to pass multiple entries to the call, since the issue was opened we have made a few changes around how queries are made, and the `givenPortOnly`, `portCache` and `noBreadthOrder` can greatly affect the performance of it, as most of the time is spent finding the right port rather than the query processing taking a long time (this can still be improved).
