### ISSUE TITLE
feat: finalize the 5.0.0 release.

### ISSUE THREAD

**Issue by CosminPerRam** [gamedig/node-gamedig#528]
More than a week ago we finally released `5.0.0-beta.0`!

And now, to get it out of beta we would need to:
- Fix the remaining failing CI gids tests (#374).
Until then we'll have time to reconsider the rules to maybe have better-formatting ones (#514) or add an equivalent (aliasing from #487).
- Decide the default behaviour for games that run multiple query types (#370).

It would be nice to add a 'version' stabilized field (#468) but could come later on as a backwards compatible update.

Feel free to mention any thoughts regarding finalizing this major version.

**Comment by podrivo** [comment]
CI GIDs testing depends on the Rust repo. Here's the issue about this: https://github.com/gamedig/rust-gamedig/issues/184

I'm all in favor of adding game aliases for a better usability of the library, as well as having compatibility of GIDs, even if we decide to change game IDs naming. There's more examples on the PR (https://github.com/gamedig/node-gamedig/pull/487). Happy to update it for the latest version!

—

I can start working on the 'version' stabilized field, as this might be an easy one to tackle.

—

Another one that might be interesting for us to start talking, but not necessarily be part of v5, is the use of RCON.
I'm not sure if RCON should be part of GameDig, but it's a good debate to have with the community, because it's been asked since 2016 (https://github.com/gamedig/node-gamedig/issues/46).

So the question is: should we support RCON or not?

I know you can query more info using RCON, but the main feature is to remote control the server, meaning you can execute a variety of commands to manage your server. I personally think this is out of scope of GameDig, but it would be good to know how others think about it.

**Comment by CosminPerRam** [comment]
> should we support RCON or not

Yes.

> I know you can query more info using RCON, but the main feature is to remote control the server, meaning you can execute a variety of commands to manage your server. I personally think this is out of scope of GameDig, but it would be good to know how others think about it.

We would use RCON in the same scope as we have done so far: just to query servers, nothing more (like remote control).

**Comment by podrivo** [comment]
About naming, if we move forward with the `alias` for games, should we kill `old_id` in favor of `alias`?

**Comment by CosminPerRam** [comment]
> Another one to maybe consider, is using the Steam API to query servers

A possible nice feature to add later on.

> About naming, if we move forward with the alias for games, should we kill old_id in favor of alias?

No, renaming old_id to alias could confuse stuff and that word wouldn't really represent of what it is.

**Comment by podrivo** [comment]
I'm asking this, because it might have conflicting issues when having both options in a game.
For example:

```
hiddendangerous2: {
  name: 'Hidden & Dangerous 2',
  release_year: 2003,
  options: {
    port: 11001,
    port_query_offset: 3,
    protocol: 'gamespy1'
  },
  extra: {
    old_id: 'had2',
    alias: 'had2'
  }
}
```

**Comment by podrivo** [comment]
Here are the PRs about top level `version` and `games.extra.alias`:

- [feat: Add version as a top level field #532](https://github.com/gamedig/node-gamedig/pull/532)
- [feat: Add game type alias #487](https://github.com/gamedig/node-gamedig/pull/487)
