### ISSUE TITLE
SOCKS Proxy Support

### ISSUE THREAD

**Issue by xpyctumo** [gamedig/node-gamedig#68]
Hello. Do you want add any proxy support?

**Comment by sonicsnes** [comment]
Do you mean ability to check server status through an http / SOCKS proxy server?

**Comment by xpyctumo** [comment]
Yes, via SOCKS proxy

**Comment by sonicsnes** [comment]
Unlikely. Sending UDP packets over socks is not very easy ([here's a description](https://superuser.com/questions/1191935/udp-traffic-through-socks/1192963)), and even then, it has a lot of limitations.

Since many SOCKS proxies don't support `UDP ASSOCIATE`, and most production servers aren't going to be behind a proxy, it sounds like a lot of effort for little payoff. I'm open to pull requests, but it might not even be worth complicating the code to implement.

**Comment by mmorrisontx** [comment]
Unlikely we'll ever get to this due to lack of interest. If anyone has a vested interest and a concrete idea of how this would actually work with UDP protocols, feel free to reopen with an implementation plan.
